/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author nidhinair
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel WorkArea;
    private PersonDirectory personDirectory;
    private Person person;
    
    public ViewJPanel(JPanel WorkArea,PersonDirectory personDirectory,Person person ) {
        initComponents();
        this.WorkArea = WorkArea;
        this.person = person;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUnitNumberW = new javax.swing.JLabel();
        txtUnitNumberW = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblCityW = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        txtCityW = new javax.swing.JTextField();
        lblStreetAddress = new javax.swing.JLabel();
        lblPhoneNumberW = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        txtPhoneNumberW = new javax.swing.JTextField();
        txtStreetAddress = new javax.swing.JTextField();
        lblStateW = new javax.swing.JLabel();
        txtUnitNumber = new javax.swing.JTextField();
        txtStateW = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblZipCode = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblStreetAddressW = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtStreetAddressW = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblZipCodeW = new javax.swing.JLabel();
        lblSocialSecurityNumber = new javax.swing.JLabel();
        txtZipCodeW = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        lblUnitNumberW.setText("Unit Number");

        lblCityW.setText("City");

        lblHomeAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblHomeAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeAddress.setText("Home Address");

        lblStreetAddress.setText("Street Address");

        lblPhoneNumberW.setText("Phone Number");

        lblUnitNumber.setText("Unit Number");

        lblStateW.setText("State");

        lblCity.setText("City");

        lblState.setText("State");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Person");

        lblPhoneNumber.setText("Phone Number");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblZipCode.setText("Zip Code");

        lblFirstName.setText("First Name");

        lblWorkAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblWorkAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkAddress.setText("Work Address");

        lblLastName.setText("Last Name");

        lblStreetAddressW.setText("Street Address");

        lblZipCodeW.setText("Zip Code");

        lblSocialSecurityNumber.setText("Social Security Number");

        lblAge.setText("Age");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHomeAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStreetAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtZipCode)
                                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPhoneNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUnitNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(txtUnitNumber)
                                    .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtState)))
                            .addComponent(lblWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCityW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCityW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStreetAddressW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStreetAddressW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtZipCodeW)
                                    .addComponent(lblPhoneNumberW, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtPhoneNumberW)
                                    .addComponent(lblZipCodeW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnitNumberW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUnitNumberW)
                                    .addComponent(lblStateW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStateW))))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate))
                        .addGap(295, 295, 295))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialSecurityNumber)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(lblUnitNumber)
                    .addComponent(lblZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(lblState)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStreetAddressW)
                        .addComponent(lblUnitNumberW))
                    .addComponent(lblZipCodeW, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddressW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZipCodeW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitNumberW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityW)
                    .addComponent(lblPhoneNumberW)
                    .addComponent(lblStateW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumberW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addGap(144, 144, 144))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void refreshTextFields() {
    // Handle basic fields
    txtFirstName.setText(person.getFirstName() != null ? person.getFirstName() : "");
    txtLastName.setText(person.getLastName() != null ? person.getLastName() : "");
    txtSocialSecurityNumber.setText(person.getSocialSecurityNumber() != null ? person.getSocialSecurityNumber() : "");
    txtAge.setText(Integer.toString(person.getAge()));

    // Handle home address fields
    txtStreetAddress.setText(person.getHomeAddress().getStreetAddress() != null ? person.getHomeAddress().getStreetAddress() : "");
    txtUnitNumber.setText(person.getHomeAddress().getUnitNumber() != null ? person.getHomeAddress().getUnitNumber() : "");
    txtCity.setText(person.getHomeAddress().getCity() != null ? person.getHomeAddress().getCity() : "");

    // Use new String(char[]) safely for state, with null check
    txtState.setText(person.getHomeAddress().getState() != null ? new String(person.getHomeAddress().getState()) : "");

    txtZipCode.setText(person.getHomeAddress().getZipCode() != 0 ? Integer.toString(person.getHomeAddress().getZipCode()) : "");
    txtPhoneNumber.setText(person.getHomeAddress().getPhoneNumber() != 0 ? Long.toString(person.getHomeAddress().getPhoneNumber()) : "");

    // Handle work address fields
    txtStreetAddressW.setText(person.getWorkAddress().getStreetAddress() != null ? person.getWorkAddress().getStreetAddress() : "");
    txtUnitNumberW.setText(person.getWorkAddress().getUnitNumber() != null ? person.getWorkAddress().getUnitNumber() : "");
    txtCityW.setText(person.getWorkAddress().getCity() != null ? person.getWorkAddress().getCity() : "");

    // Use new String(char[]) safely for work state, with null check
    txtStateW.setText(person.getWorkAddress().getState() != null ? new String(person.getWorkAddress().getState()) : "");

    txtZipCodeW.setText(person.getWorkAddress().getZipCode() != 0 ? Integer.toString(person.getWorkAddress().getZipCode()) : "");
    txtPhoneNumberW.setText(person.getWorkAddress().getPhoneNumber() != 0 ? Long.toString(person.getWorkAddress().getPhoneNumber()) : "");
}

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Navigate back to previous panel
        WorkArea.remove(this);
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String socialSecurityNumber = txtSocialSecurityNumber.getText();
        String City = txtCity.getText();
        String CityW = txtCityW.getText();
        String StreetAddress = txtStreetAddress.getText();
        String StreetAddressW = txtStreetAddressW.getText();
        String UnitNumber = txtUnitNumber.getText();
        String UnitNumberW = txtUnitNumberW.getText();
        
        // Primitive data: Ensure validation for integers and long
        int age;
        try {
            age = Integer.parseInt(txtAge.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Age. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int zipCode;
        try {
            zipCode = Integer.parseInt(txtZipCode.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Zip Code. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        long phoneNumber;
        try {
            phoneNumber = Long.parseLong(txtPhoneNumber.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Work Address fields
        int zipCodeW;
        try {
            zipCodeW = Integer.parseInt(txtZipCodeW.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Work Zip Code. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        long phoneNumberW;
        try {
            phoneNumberW = Long.parseLong(txtPhoneNumberW.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Work Phone Number. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get char array for state
        char[] state = txtState.getText().toCharArray();
        char[] stateW = txtStateW.getText().toCharArray();

        // Check mandatory fields
        if (firstName.isBlank() || lastName.isBlank() || socialSecurityNumber.isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setSocialSecurityNumber(socialSecurityNumber);
        person.setAge(age);
        
        
        /*Address homeAddress = new Address();
        homeAddress.setCity(City);
        homeAddress.setState(state);
        homeAddress.setStreetAddress(StreetAddress);
        homeAddress.setPhoneNumber(phoneNumber);
        homeAddress.setUnitNumber(UnitNumber);
        homeAddress.setZipCode(zipCode);
        
        person.setHomeAddress(homeAddress);*/
        Address homeAddress = new Address(StreetAddress,UnitNumber,City,state,zipCode,phoneNumber);
        person.setHomeAddress(homeAddress);
        Address workAddress = new Address(StreetAddressW,UnitNumberW,CityW,stateW,zipCodeW,phoneNumberW);
        person.setWorkAddress(workAddress);
        /*person.setCity(City);
        person.setState(state);
        person.setStreetAddress(StreetAddress);
        person.setPhoneNumber(phoneNumber);
        person.setZipCode(zipCode);
        person.setUnitNumber(UnitNumber);
        person.setCity(CityW);
        person.setState(stateW);
        person.setStreetAddress(StreetAddressW);
        person.setPhoneNumber(phoneNumberW);
        person.setZipCode(zipCodeW);
        person.setUnitNumber(UnitNumberW);*/
        
        JOptionPane.showMessageDialog(null,"Account successfully updated","Warning",JOptionPane.WARNING_MESSAGE);
        
        setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCityW;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberW;
    private javax.swing.JLabel lblSocialSecurityNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStateW;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblStreetAddressW;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblUnitNumberW;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblZipCodeW;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCityW;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumberW;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStateW;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtStreetAddressW;
    private javax.swing.JTextField txtUnitNumber;
    private javax.swing.JTextField txtUnitNumberW;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtZipCodeW;
    // End of variables declaration//GEN-END:variables

    private void setViewMode() {
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtSocialSecurityNumber.setEnabled(false);
        txtAge.setEnabled(false);
        txtStreetAddress.setEnabled(false);
        txtUnitNumber.setEnabled(false);
        txtCity.setEnabled(false);
        txtState.setEnabled(false);
        txtZipCode.setEnabled(false);
        txtPhoneNumber.setEnabled(false);
        txtStreetAddressW.setEnabled(false);
        txtUnitNumberW.setEnabled(false);
        txtCityW.setEnabled(false);
        txtStateW.setEnabled(false);
        txtZipCodeW.setEnabled(false);
        txtPhoneNumberW.setEnabled(false);
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }

    private void setEditMode() {
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSocialSecurityNumber.setEnabled(true);
        txtAge.setEnabled(true);
        txtStreetAddress.setEnabled(true);
        txtUnitNumber.setEnabled(true);
        txtCity.setEnabled(true);
        txtState.setEnabled(true);
        txtZipCode.setEnabled(true);
        txtPhoneNumber.setEnabled(true);
        txtStreetAddressW.setEnabled(true);
        txtUnitNumberW.setEnabled(true);
        txtCityW.setEnabled(true);
        txtStateW.setEnabled(true);
        txtZipCodeW.setEnabled(true);
        txtPhoneNumberW.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }

    
}
