/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.Person;

/**
 *
 * @author nidhinair
 */
public class CreateJPanel extends javax.swing.JPanel {
    Person person;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Person p) {
        person = p;
        initComponents();
        addScrolPane();//call method to add scrolpane
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        LblDriversLicenseNo = new javax.swing.JLabel();
        LblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        LblFirstName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        LblPhoneNumber = new javax.swing.JLabel();
        txtDriversLicenseNo = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        txtDriversLicenseState = new javax.swing.JTextField();
        LblDriversLicenseState = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        LblSocialSecurityNumber = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        LblAge = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        LblDateofBirth = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        LblOccupation = new javax.swing.JLabel();
        txtDateofBirth = new javax.swing.JTextField();
        LblNationality = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();
        txtHobby = new javax.swing.JTextField();
        LblHobby = new javax.swing.JLabel();
        LblMartialStatus = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        LblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListMaritalStatus = new javax.swing.JList<>();

        LblDriversLicenseNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblDriversLicenseNo.setText("Drivers License Number");

        LblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblLastName.setText("Last Name");

        LblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblFirstName.setText("First Name");

        LblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblPhoneNumber.setText("Phone Number");

        LblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblEmail.setText("Email");

        LblDriversLicenseState.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblDriversLicenseState.setText("Drivers License State");

        LblSocialSecurityNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblSocialSecurityNumber.setText("Social Security Number");

        LblAge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblAge.setText("Age");

        LblDateofBirth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblDateofBirth.setText("Date of Birth");

        LblOccupation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblOccupation.setText("Occupation");

        txtDateofBirth.setText("DD/MM/YYYY");

        LblNationality.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblNationality.setText("Nationality");

        LblHobby.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblHobby.setText("Hobby");

        LblMartialStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblMartialStatus.setText("Martial Status");

        btnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        LblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("Create Person");
        LblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ListMaritalStatus.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Single", "Married", "Divorced", "Widowed" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListMaritalStatus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(ListMaritalStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblDriversLicenseNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblDriversLicenseState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblOccupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblDateofBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblNationality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblSocialSecurityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblHobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblMartialStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHobby)
                            .addComponent(txtSocialSecurityNumber)
                            .addComponent(txtDateofBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(txtOccupation)
                            .addComponent(txtLastName)
                            .addComponent(txtEmail)
                            .addComponent(txtDriversLicenseNo)
                            .addComponent(txtDriversLicenseState)
                            .addComponent(txtPhoneNumber)
                            .addComponent(txtAge)
                            .addComponent(txtNationality)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail)
                    .addComponent(LblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LblDriversLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtDriversLicenseNo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDriversLicenseState)
                    .addComponent(LblDriversLicenseState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LblOccupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtOccupation, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LblDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtDateofBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNationality)
                    .addComponent(LblNationality))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LblSocialSecurityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LblHobby, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtHobby, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LblMartialStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(127, 127, 127))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String FirstName = txtFirstName.getText();
        String LastName = txtLastName.getText();
        String Email = txtEmail.getText();
        String DriversLicenseNumber = txtDriversLicenseNo.getText();
        String DriversLicenseState = txtDriversLicenseState.getText();
        String PhoneNumber = txtPhoneNumber.getText();
        String Age = txtAge.getText();
        String Occupation = txtOccupation.getText();
        String DateOfBirth = txtDateofBirth.getText();
        String Nationality = txtNationality.getText();
        String SocialSecurityNumber = txtSocialSecurityNumber.getText();
        String Hobby = txtHobby.getText();
        String MaritalStatus = ListMaritalStatus.getSelectedValue();;
        
        person.setFirst_Name(FirstName);
        person.setLast_Name(LastName);
        person.setEmail(Email);
        person.setDriver_License_Number(DriversLicenseNumber);
        person.setDriver_License_State(DriversLicenseState);
        person.setPhone(PhoneNumber);
        person.setAge(Age);
        person.setOccupation(Occupation);
        person.setDateOfBirth(DateOfBirth);
        person.setNationality(Nationality);
        person.setSocial_Security_Number(SocialSecurityNumber);
        person.setHobby(Hobby);
        person.setMaritalStatus(MaritalStatus);
        
        JOptionPane.showMessageDialog(this, "Person Information Saved", "Success", JOptionPane.PLAIN_MESSAGE);
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtDriversLicenseNo.setText("");
        txtDriversLicenseState.setText("");
        txtPhoneNumber.setText("");
        txtAge.setText("");
        txtOccupation.setText("");
        txtDateofBirth.setText("");
        txtNationality.setText("");
        txtSocialSecurityNumber.setText("");
        txtHobby.setText("");
          
        
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAge;
    private javax.swing.JLabel LblDateofBirth;
    private javax.swing.JLabel LblDriversLicenseNo;
    private javax.swing.JLabel LblDriversLicenseState;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFirstName;
    private javax.swing.JLabel LblHobby;
    private javax.swing.JLabel LblLastName;
    private javax.swing.JLabel LblMartialStatus;
    private javax.swing.JLabel LblNationality;
    private javax.swing.JLabel LblOccupation;
    private javax.swing.JLabel LblPhoneNumber;
    private javax.swing.JLabel LblSocialSecurityNumber;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JList<String> ListMaritalStatus;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDriversLicenseNo;
    private javax.swing.JTextField txtDriversLicenseState;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHobby;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSocialSecurityNumber;
    // End of variables declaration//GEN-END:variables

    private void addScrolPane() {
        JPanel formPanel = new JPanel();
        formPanel.setLayout(new GridLayout(0, 2, 10, 10)); // 0 rows, 2 columns, gaps of 10 pixels

        // Add components to the form panel (you can copy from initComponents)
        formPanel.add(new JLabel("First Name"));
        formPanel.add(txtFirstName);

        formPanel.add(new JLabel("Last Name"));
        formPanel.add(txtLastName);

        formPanel.add(new JLabel("Email"));
        formPanel.add(txtEmail);

        formPanel.add(new JLabel("Drivers License Number"));
        formPanel.add(txtDriversLicenseNo);

        formPanel.add(new JLabel("Drivers License State"));
        formPanel.add(txtDriversLicenseState);

        formPanel.add(new JLabel("Phone Number"));
        formPanel.add(txtPhoneNumber);

        formPanel.add(new JLabel("Age"));
        formPanel.add(txtAge);

        formPanel.add(new JLabel("Occupation"));
        formPanel.add(txtOccupation);

        formPanel.add(new JLabel("Date of Birth"));
        formPanel.add(txtDateofBirth);

        formPanel.add(new JLabel("Nationality"));
        formPanel.add(txtNationality);

        formPanel.add(new JLabel("Social Security Number"));
        formPanel.add(txtSocialSecurityNumber);

        formPanel.add(new JLabel("Hobby"));
        formPanel.add(txtHobby);

        formPanel.add(new JLabel("Marital Status"));
        formPanel.add(ListMaritalStatus);
        formPanel.add(btnSave);

        setLayout(new BorderLayout());
        
        // Wrap the form panel in a JScrollPane
        JScrollPane scrollPane = new JScrollPane(formPanel);
        add(scrollPane, BorderLayout.CENTER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setPreferredSize(new Dimension(1000, 800)); // Set preferred size

        // Set layout for the main panel and add the scroll pane
        this.setLayout(new BorderLayout());
        this.add(LblTitle, BorderLayout.NORTH);
        this.add(scrollPane, BorderLayout.CENTER);
    }

    
}
