/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.Person;

/**
 *
 * @author nidhinair
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewJPanel(Person p) {
        initComponents();
        person = p;
        displayPerson();
        addScrolPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNationality = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtHobby = new javax.swing.JTextField();
        LblDriversLicenseNo = new javax.swing.JLabel();
        LblLastName = new javax.swing.JLabel();
        LblHobby = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        LblFirstName = new javax.swing.JLabel();
        LblMaritalStatus = new javax.swing.JLabel();
        txtMaritalStatus = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        LblPhoneNumber = new javax.swing.JLabel();
        txtDriversLicenseNo = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        txtDriversLicenseState = new javax.swing.JTextField();
        LblDriversLicenseState = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        LblSocialSecurityNumber = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        LblAge = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        LblDateofBirth = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        LblOccupation = new javax.swing.JLabel();
        txtDateofBirth = new javax.swing.JTextField();
        LblNationality = new javax.swing.JLabel();
        LblTitleV = new javax.swing.JLabel();

        LblDriversLicenseNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblDriversLicenseNo.setText("Drivers License Number");

        LblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblLastName.setText("Last Name");

        LblHobby.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblHobby.setText("Hobby");

        LblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblFirstName.setText("First Name");

        LblMaritalStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblMaritalStatus.setText("Marital Status");

        LblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblPhoneNumber.setText("Phone Number");

        LblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblEmail.setText("Email");

        LblDriversLicenseState.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblDriversLicenseState.setText("Drivers License State");

        LblSocialSecurityNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblSocialSecurityNumber.setText("Social Security Number");

        LblAge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblAge.setText("Age");

        LblDateofBirth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblDateofBirth.setText("Date of Birth");

        LblOccupation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblOccupation.setText("Occupation");

        LblNationality.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblNationality.setText("Nationality");

        LblTitleV.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        LblTitleV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitleV.setText("View Person");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblDriversLicenseNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(LblDriversLicenseState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblOccupation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblDateofBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblNationality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblSocialSecurityNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblHobby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblMaritalStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addComponent(txtLastName)
                    .addComponent(txtEmail)
                    .addComponent(txtDriversLicenseNo)
                    .addComponent(txtDriversLicenseState)
                    .addComponent(txtPhoneNumber)
                    .addComponent(txtAge)
                    .addComponent(txtOccupation)
                    .addComponent(txtDateofBirth)
                    .addComponent(txtNationality)
                    .addComponent(txtSocialSecurityNumber)
                    .addComponent(txtHobby)
                    .addComponent(txtMaritalStatus)))
            .addComponent(LblTitleV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitleV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFirstName)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDriversLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDriversLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDriversLicenseState, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtDriversLicenseState, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblOccupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOccupation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDateofBirth)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSocialSecurityNumber)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblHobby)
                    .addComponent(txtHobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblMaritalStatus)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAge;
    private javax.swing.JLabel LblDateofBirth;
    private javax.swing.JLabel LblDriversLicenseNo;
    private javax.swing.JLabel LblDriversLicenseState;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFirstName;
    private javax.swing.JLabel LblHobby;
    private javax.swing.JLabel LblLastName;
    private javax.swing.JLabel LblMaritalStatus;
    private javax.swing.JLabel LblNationality;
    private javax.swing.JLabel LblOccupation;
    private javax.swing.JLabel LblPhoneNumber;
    private javax.swing.JLabel LblSocialSecurityNumber;
    private javax.swing.JLabel LblTitleV;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDriversLicenseNo;
    private javax.swing.JTextField txtDriversLicenseState;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHobby;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMaritalStatus;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSocialSecurityNumber;
    // End of variables declaration//GEN-END:variables

    private void displayPerson(){
        txtFirstName.setText(person.getFirst_Name());
        txtLastName.setText(person.getLast_Name());
        txtEmail.setText(person.getEmail());
        txtDriversLicenseNo.setText(person.getDriver_License_Number());
        txtDriversLicenseState.setText(person.getDriver_License_State());
        txtPhoneNumber.setText(person.getPhone());
        txtAge.setText(person.getAge());
        txtOccupation.setText(person.getOccupation());
        txtDateofBirth.setText(person.getDateOfBirth());
        txtNationality.setText(person.getNationality());
        txtSocialSecurityNumber.setText(person.getSocial_Security_Number());
        txtHobby.setText(person.getHobby());
        txtMaritalStatus.setText(person.getMaritalStatus());
    }
    
    private void addScrolPane() {
    JPanel formPanel = new JPanel();
    formPanel.setLayout(new GridLayout(0, 2, 20, 20)); // 0 rows, 2 columns, gaps of 10 pixels

    // Use existing JTextFields to display the person's information
    formPanel.add(new JLabel("First Name"));
    formPanel.add(txtFirstName);
    formPanel.add(new JLabel("Last Name"));
    formPanel.add(txtLastName);
    formPanel.add(new JLabel("Email"));
    formPanel.add(txtEmail);
    formPanel.add(new JLabel("Drivers License Number"));
    formPanel.add(txtDriversLicenseNo);
    formPanel.add(new JLabel("Drivers License State"));
    formPanel.add(txtDriversLicenseState);
    formPanel.add(new JLabel("Phone Number"));
    formPanel.add(txtPhoneNumber);
    formPanel.add(new JLabel("Age"));
    formPanel.add(txtAge);
    formPanel.add(new JLabel("Occupation"));
    formPanel.add(txtOccupation);
    formPanel.add(new JLabel("Date of Birth"));
    formPanel.add(txtDateofBirth);
    formPanel.add(new JLabel("Nationality"));
    formPanel.add(txtNationality);
    formPanel.add(new JLabel("Social Security Number"));
    formPanel.add(txtSocialSecurityNumber);
    formPanel.add(new JLabel("Hobby"));
    formPanel.add(txtHobby);
    formPanel.add(new JLabel("Marital Status"));
    formPanel.add(txtMaritalStatus);

    // Wrap the form panel in a JScrollPane
    JScrollPane scrollPane = new JScrollPane(formPanel);
    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    scrollPane.setPreferredSize(new Dimension(600, 400)); // Set preferred size

    // Set layout for the main panel and add the scroll pane
    this.setLayout(new BorderLayout());
    this.add(LblTitleV, BorderLayout.NORTH);
    this.add(scrollPane, BorderLayout.CENTER);
    } 
    
}
    
        
